name: Update YAML on MD Change

on:
  push:
    paths:
      - 'scripts/Description.md'  # Specify your Markdown file here

jobs:
  update-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Update YAML file
        run: |
          cd scripts
          python3 -m pip install --upgrade pip
          pip3 install pyyaml
          python3 Update_Json.py
          
      - name: Commit changes
        run: |
          cd scripts
          git config --global user.email "SESA768583@se.com"
          git config --global user.name "manish-maller-se"
          git add .
          git commit -m "Update YAML description from Markdown changes" || echo "No changes to commit"
          git push
