name: Update YAML on MD Change

on:
  push:
    paths:
      - 'scripts/Description.md'  # Specify your Markdown file here

jobs:
  update-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update YAML file
        run: |
          cd scripts
          # Read the content of the Markdown file
          content=$(cat Description.md)
          
          # Update the YAML file with the new description
          echo "description: \"$content\"" > original.yaml

      - name: Commit changes
        run: |
          cd scripts
          git add original.yaml
          git commit -m "Update YAML description from Markdown changes" || echo "No changes to commit"
          git push
